from __future__ import annotations

from time import perf_counter

from prometheus_client import CONTENT_TYPE_LATEST, Counter, Gauge, Histogram, Info, generate_latest


REQUEST_COUNT = Counter(
    "vision_classifier_requests_total",
    "Total API requests processed.",
    labelnames=("method", "endpoint", "status_code"),
)
REQUEST_LATENCY = Histogram(
    "vision_classifier_request_latency_seconds",
    "API request latency in seconds.",
    labelnames=("method", "endpoint"),
)
PREDICTION_COUNT = Counter(
    "vision_classifier_predictions_total",
    "Number of predictions generated by the service.",
    labelnames=("backend",),
)
ERROR_COUNT = Counter(
    "vision_classifier_errors_total",
    "Number of API errors raised by the service.",
    labelnames=("endpoint",),
)
MODEL_LOADED = Gauge(
    "vision_classifier_model_loaded",
    "Whether the active model is loaded into memory.",
)
MODEL_INFO = Info("vision_classifier_model", "Current deployed model metadata.")


def begin_request_timer() -> float:
    return perf_counter()


def observe_request(method: str, endpoint: str, status_code: int, started_at: float) -> None:
    REQUEST_COUNT.labels(method=method, endpoint=endpoint, status_code=str(status_code)).inc()
    REQUEST_LATENCY.labels(method=method, endpoint=endpoint).observe(perf_counter() - started_at)


def record_prediction(backend: str, count: int = 1) -> None:
    PREDICTION_COUNT.labels(backend=backend).inc(count)


def record_error(endpoint: str) -> None:
    ERROR_COUNT.labels(endpoint=endpoint).inc()


def update_model_status(loaded: bool, model_version: str, backend: str) -> None:
    MODEL_LOADED.set(1 if loaded else 0)
    MODEL_INFO.info({"model_version": model_version, "backend": backend})


def render_metrics() -> tuple[bytes, str]:
    return generate_latest(), CONTENT_TYPE_LATEST